## Workflow



| Steps   |      description     |  metric |
|----------|:-------------:|------:|
| Order received | Day 1 |  Number of Orders, percentage of correct filled orders   |
| Order processing and shipping phase |    normally 2 Days, limited visibility   |   percentage of right processing, preparation/processing time, packaging time,  total shipping time |
| order shipped | delivered by external truck comapny on following day if possible, limited visibility |  delivery time  |
|delivered | customer received order, average 3 days time, unclear if thats true due to qr scan | total order time
    


------------------------------------------------------------
- claim:  complete data on the **Order Date** and the On **Truck Scan Date** --> check if its true.  

- but:  limited visibility of what happens in between or after --> when the truck leaves its unknown how much time it takes. 

- they have sent into the warehouse to record the **Ready to Ship Date** for as many orders as possible -> missing values

In [1]:
import pandas as pd

In [5]:
orders_raw = pd.read_excel('data/Muesli Project raw data.xlsx', sheet_name='Orders')
orders_raw.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18
0,Index,Order ID,Order Date,Ship Mode,Customer ID,Customer Name,Origin Channel,Country/Region,City,State,Postal Code,Region,Category,Sub-Category,Product ID,Sales,Quantity,Discount,Profit
1,27,CA-2019-121755,2019-01-16 00:00:00,Second Class,EH-13945,Eric Hoffmann,Email,United States,Los Angeles,California,90049,West,Special Projects Muesil,Gluten Free,TEC-AC-10003027,90.57,3,0,11.7741
2,45,CA-2019-118255,2019-03-11 00:00:00,First Class,ON-18715,Odella Nelson,Sales,United States,Eagan,Minnesota,55122,Central,Special Projects Muesil,Gluten Free,TEC-AC-10000171,45.98,2,0,19.7714
3,48,CA-2019-169194,2019-06-20 00:00:00,Standard Class,LH-16900,Lena Hernandez,Email,United States,Dover,Delaware,19901,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,45,3,0,4.95
4,60,CA-2019-111682,2019-06-17 00:00:00,First Class,TB-21055,Ted Butterfield,Email,United States,Troy,New York,12180,East,Special Projects Muesil,Gluten Free,TEC-AC-10002167,30,2,0,3.3

In [2]:
campaign_raw = pd.read_excel('data/Muesli Project raw data.xlsx', sheet_name='Campaign Data')
campaign_raw.head()

         Order ID Arrival Scan Date     Customer Name
0  CA-2019-109666        2019-05-03      Kunst Miller
1  CA-2019-138933        2019-05-03       Jack Lebron
2  CA-2019-130001        2019-05-03  Heather Kirkland
3  CA-2019-113061        2019-05-06         Ed Ludwig
4  CA-2019-162138        2019-05-06       Grace Kelly

In [ ]:
# Your code here — .info(), .describe()               #the company said data over past few years, its only 1 year
campaign_raw.info()
display(campaign_raw.describe())

<class 'pandas.DataFrame'>
RangeIndex: 333 entries, 0 to 332
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order ID           333 non-null    str
 1   Arrival Scan Date  333 non-null    datetime64[us]
 2   Customer Name      333 non-null    str
dtypes: datetime64[us](1), str(2)
memory usage: 7.9 KB

                Arrival Scan Date
count                         333
mean   2019-10-14 19:36:12.972973
min           2019-05-03 00:00:00
25%           2019-09-09 00:00:00
50%           2019-10-21 00:00:00
75%           2019-12-16 00:00:00
max           2020-05-15 00:00:00

In [ ]:
campaign_raw.isnull().sum() #no missing values

Order ID             0
Arrival Scan Date    0
Customer Name        0
dtype: int64

In [ ]:
campaign_raw.duplicated().sum() #no duplicates either

np.int64(0)

In [3]:
order_process_raw = pd.read_excel('data/Muesli Project raw data.xlsx', sheet_name='Order Process Data')
order_process_raw.head()

   Row ID        Order ID Order Date On Truck Scan Date            Ship Mode
0    3074  CA-2019-125206 2019-01-03         2019-01-07              Express
1    4919  CA-2019-160304 2019-01-02         2019-01-09  Standard Processing
2    4920  CA-2019-160304 2019-01-02         2019-01-09  Standard Processing
3    8604  US-2019-116365 2019-01-03         2019-01-09  Standard Processing
4    8605  US-2019-116365 2019-01-03         2019-01-09  Standard Processing

In [4]:
intern_data_raw = pd.read_excel('data/Muesli Project raw data.xlsx', sheet_name='InternData Study')
intern_data_raw.head()

         Order ID Ready to Ship Date Pickup Date
0  CA-2019-116540         2019-09-02  2019-09-03
1  CA-2019-116540         2019-09-02  2019-09-03
2  CA-2019-129847         2019-09-04  2019-09-04
3  CA-2019-129630         2019-09-04  2019-09-04
4  CA-2019-106278         2019-09-05  2019-09-06